name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the action on a push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: SSH into server and deploy application
      run: |
        sshpass -p '${{secrets.SERVER_PASSWORD}}' ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} -p ${{secrets.SERVER_PORT}} <<'ENDSSH'
          cd ${{secrets.SERVER_PATH}}
          git pull
          npm install
          npm run build
        ENDSSH